# Generated by Django 5.0.7 on 2024-07-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='added_by',
        ),
    ]
